services:
  - type: web
    name: automentor
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: automentor-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        value: AQQRFqiUJuokmeHal83UnsJrb_oRoZ6ynJ2eBW1RA3tMKDojrT4y0KNa1SffdoE1MMG9HOFKCJpydUTB
      - key: PAYPAL_CLIENT_SECRET
        value: EAkvlZmB_DqTu_KyBw2Fb_xupIJrt549e321Pd1bsWzmuAZrohQX10er1CFRiYjObtRiHpxfeoOyZRqU
      - key: SMTP_USER
        value: wiktoriatopajew@gmail.com
      - key: SMTP_PASS
        value: tjcnwadgvaiolgdo
      # Logger Configuration - Production Minimal
      - key: LOG_LEVEL
        value: warn
      - key: ENABLE_SESSION_LOGS
        value: false
      - key: ENABLE_API_LOGS
        value: false
      - key: ENABLE_SQL_LOGS
        value: false
      - key: ENABLE_ADMIN_LOGS
        value: true
      - key: ENABLE_LIVE_DATA_LOGS
        value: false
      - key: ENABLE_PAYMENT_LOGS
        value: true
    healthCheckPath: /api/health

databases:
  - name: automentor-db
    databaseName: automentor
    plan: free